name: Check Lua Formatting
on:
  push:
  pull_request:

permissions:
  contents: read

concurrency:
  group: stylua-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  stylua-check:
    name: Stylua Check
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
      - name: StyLua Check
        uses: JohnnyMorganz/stylua-action@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: v2.5.2
          args: --check .
