name: Tests
on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  fast:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v7
      - uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: v0.12.2
      - run: make test-setup
      - run: make test
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: .test-results/
          include-hidden-files: true
